
import java.awt.Graphics2D;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TenantTerror
//  @ File Name : BasicBroker.java
//  @ Date : 11/11/2014
//  @ Author : Serhat CAN
//
//

public class BasicBroker extends Broker {

	/*
	 * BasicBroker is designed for brokers that have money between 0-750. Their
	 * initial style is decorated as cyan circle.
	 */

	public BasicBroker(Strategy strategy, Simulation sim) {
		super(strategy, sim);
		// TODO Auto-generated constructor stub
	}

	public boolean act(House house) {
		return super.act(house);
	}

	@Override
	public void draw(Graphics2D g2d) {
		super.draw(g2d);

	}

	@Override
	public void step(double deltaTime) {

		strategy.step(this, deltaTime);

	}
}
