
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TenantTerror
//  @ File Name : BrokerDecorator.java
//  @ Date : 11/11/2014
//  @ Author : Serhat CAN
//
//

public abstract class BrokerDecorator extends Broker {
	public Broker component; // could be protected

	public BrokerDecorator(Broker broker) {
		super(null, null);
		component = broker;
	}

	public double getX() {
		return this.component.x;
	}

	public double getY() {
		return this.component.y;
	}

	public int getMoney() {
		return this.component.getMoney();
	}

}
