
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TenantTerror
//  @ File Name : BrokerFactory.java
//  @ Date : 11/11/2014
//  @ Author : Serhat CAN
//
//

public class BrokerFactory extends EntityFactory {

	@Override
	public Entity produce(Strategy strategy, Simulation sim) {

		return new BasicBroker(strategy, sim);
	}
}