
import java.util.List;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TenantTerror
//  @ File Name : CheapestFirst.java
//  @ Date : 11/11/2014
//  @ Author : Serhat CAN
//
//

public class CheapestFirst extends Strategy {

	Entity cheapest;

	int cheapestPrice;

	Simulation s;
	DO dObject;

	public double direction;

	public double targetX;
	public double targetY;

	public CheapestFirst(Simulation simulation) {
		isFinished = false;
		cheapest = null;
		dObject = new DO();
		s = Simulation.getInstance();
		cheapestPrice = 3000;
	}

	@Override
	public void step(Entity e, double deltaTime) {

		List<Entity> temp = s.entities;

		// find the chepeast house
		for (Entity en : temp) {
			if (en instanceof House) {
				if (((House) en).getPrice() < cheapestPrice) {
					cheapest = en;
				}
			}
		}

		targetX = cheapest.x;
		targetY = cheapest.y;

		// target is known

		double deltaX = targetX - e.x;
		double deltaY = targetY - e.y;

		double distance = Math.sqrt(deltaX * deltaX + deltaY * deltaY);

		double stepX = (deltaX / distance) * e.speed * deltaTime;
		double stepY = (deltaY / distance) * e.speed * deltaTime;

		if (distance < e.speed) {
			stepX = deltaX;
			stepY = deltaY;

		}

		e.x += stepX;
		e.y += stepY;

		// check for correct place and do your job cause you found a house
		if (distance == 0.0) {

			House hous = (House) cheapest;

			if (hous != null) {

				// just act
				if (e.act(hous))
					isFinished = true;

			}
		}

	}

}
