
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;

import javax.imageio.ImageIO;
import javax.swing.JPanel;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TenantTerror
//  @ File Name : Display.java
//  @ Date : 11/11/2014
//  @ Author : Serhat CAN
//
//

public class Display extends JPanel {

	Simulation simulation;

	public Image backgroundImage = ImageIO.read(getClass().getResource(
			DO.backgroundImage));

	public Image smallImage = ImageIO.read(getClass()
			.getResource(DO.smallImage));

	/**
	 * default serialVerisonUID
	 */
	private static final long serialVersionUID = 1L;

	public Display(Simulation simulation) throws Exception {
		setBackground(Color.white);
		this.simulation = simulation;
	}

	public Dimension getPreferredSize() {
		return new Dimension(DO.windowWidth, DO.windowHeight);

	}

	public void paintComponent(Graphics g) {

		super.paintComponent(g);

		// Image drawings
		g.drawImage(backgroundImage, 200, 0, this);

		g.drawImage(smallImage, 20, 520, 150, 45, this);

		// 2D Graphics object for 2d objects

		Graphics2D g2d = (Graphics2D) g;

		// Draw information display area

		g2d.drawLine(DO.infoPanelWidth, 0, DO.infoPanelWidth, DO.windowHeight);

		// Display information

		int info_x = 10;
		int info_y = 30;

		Font defaultFont = g2d.getFont();
		Font newFont = new Font("Calibri", Font.ROMAN_BASELINE, 14);

		g2d.setFont(newFont);

		g2d.drawString("NumberOfHouses : " + simulation.numOfHouses, info_x,
				info_y);

		info_y += 30;
		g2d.drawString("NumberOfBrokers : " + simulation.numOfBrokers, info_x,
				info_y);

		info_y += 30;
		g2d.drawString("NumberOfStudents : " + simulation.numOfStudents,
				info_x, info_y);

		info_y += 30;
		g2d.drawString("# ofFlatsRentedFromOwner : "
				+ simulation.countRentedFromOwner, info_x, info_y);

		info_y += 30;
		g2d.drawString("# ofFlatsRentedFromBroker : "
				+ simulation.countRentedFromBroker, info_x, info_y);

		int totalNumOfFlats = simulation.countRentedFromBroker
				+ simulation.countRentedFromOwner;
		info_y += 30;
		g2d.drawString("Total # ofFlatsRented : " + totalNumOfFlats, info_x,
				info_y);

		info_y += 30;
		g2d.drawString("MoneySpentByStudents : "
				+ simulation.moneySpentByStudents, info_x, info_y);

		info_y += 30;
		g2d.drawString("MoneyGainedByBrokers : "
				+ simulation.moneyGainedByBrokers, info_x, info_y);

		info_y += 30;
		g2d.drawString("MoneySavedByStudents : "
				+ simulation.moneySpentByStudents, info_x, info_y);

		info_y += 320;
		g2d.drawString("Coded by Serhat CAN.", info_x, info_y);

		g2d.setFont(defaultFont);
		// Draw Houses

		for (Entity e : simulation.entities) {
			e.draw(g2d);
		}

	}

}
