
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TenantTerror
//  @ File Name : EntityFactory.java
//  @ Date : 11/11/2014
//  @ Author : Serhat CAN
//
//

public abstract class EntityFactory {
	public abstract Entity produce(Strategy strategy, Simulation sim);
}
