
import java.awt.Graphics2D;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TenantTerror
//  @ File Name : Entity.java
//  @ Date : 11/11/2014
//  @ Author : Serhat CAN
//
//

public abstract class Entity {
	public double x;
	public double y;
	public double speed;
	public Strategy strategy;

	public DO dObject;

	public Simulation simulation;

	public Entity(Strategy strategy, Simulation sim) {
		this.simulation = sim;
		this.strategy = strategy;

		dObject = new DO();

		x = dObject.randomXInGridArea();
		y = dObject.randomYInGridArea();
		speed = dObject.randomSpeed();
	}

	public abstract boolean act(House house);

	public abstract void draw(Graphics2D g2d);

	public abstract void step(double deltaTime);

}
