
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TenantTerror
//  @ File Name : FromBroker.java
//  @ Date : 11/11/2014
//  @ Author : Serhat CAN
//
//

public class FromBroker extends HouseDecorator {
	public FromBroker(House component, Simulation sim) {
		super(component, sim);

		this.component = component;
		x = component.x;
		y = component.y;
		speed = component.speed;
		strategy = component.strategy;

	}

	@Override
	public void draw(Graphics2D g2d) {
		component.x = x;
		component.y = y;
		component.speed = speed;

		component.draw(g2d);

		g2d.setColor(Color.CYAN);

		g2d.setStroke(new BasicStroke(DO.stroke));
		g2d.drawRect((int) component.x - 2, (int) component.y - 2,
				DO.radius + 4, DO.radius + 4);

	}

	@Override
	public void step(double deltaTime) {
		// TODO Auto-generated method stub
	}

	@Override
	public boolean act(House house) {
		// TODO Auto-generated method stub
		return false;
	}
}
