
import java.awt.Graphics2D;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TenantTerror
//  @ File Name : HouseDecorator.java
//  @ Date : 11/11/2014
//  @ Author : Serhat CAN
//
//

public abstract class HouseDecorator extends House {
	protected House component; // could be protected

	public HouseDecorator(House house, Simulation simulation) {
		super(simulation);

		component = house;
	}

	@Override
	public void draw(Graphics2D g2d) {
		component.draw(g2d);
	}
}
