
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TenantTerror
//  @ File Name : HouseFactory.java
//  @ Date : 11/11/2014
//  @ Author : Serhat CAN
//
//

public class HouseFactory extends EntityFactory {
	public HouseFactory() {

	}

	@Override
	public Entity produce(Strategy strategy, Simulation sim) {
		return new BasicHouse(sim);
	}
}
