
import java.util.Random;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TenantTerror
//  @ File Name : House.java
//  @ Date : 11/11/2014
//  @ Author : Serhat CAN
//

public abstract class House extends Entity {

	private boolean fromOwner;
	protected int price;
	private boolean isRented;

	private Broker broker;

	public House(Simulation sim) {
		super(null, sim);

		isRented = false;
		fromOwner = true;
		price = randomPrice();
		broker = null;
	}

	// Gets a random num between 25-1000
	private int randomPrice() {

		Random random = new Random();

		return (random.nextInt(39) + 1) * 25;
	}

	public boolean act(House house) {
		return false;
	}

	/*
	 * Getter and Setter methods
	 */
	public boolean isFromOwner() {
		return fromOwner;
	}

	public void setFromOwner(boolean fromOwner) {
		this.fromOwner = fromOwner;
	}

	public int getPrice() {
		return price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public boolean isRented() {
		return isRented;
	}

	public void setRented(boolean isRented) {
		this.isRented = isRented;
	}

	public Broker getBroker() {
		return broker;
	}

	public void setBroker(Broker broker) {
		this.broker = broker;
	}

}