
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TenantTerror
//  @ File Name : Poor.java
//  @ Date : 11/11/2014
//  @ Author : Serhat CAN
//
//

public class Poor extends BrokerDecorator {

	public Poor(Broker component) {
		super(component);
		this.component = component;
		x = component.x;
		y = component.y;
		speed = component.speed;
		strategy = component.strategy;
		setHouses(component.getHouses());
		money = component.money;
	}

	public boolean act(House house) {
		return true;
	}

	@Override
	public void draw(Graphics2D g2d) {
		component.x = x;
		component.y = y;
		component.speed = speed;
		component.setHouses(houses);
		component.money = money;

		component.draw(g2d);

		g2d.setColor(Color.PINK);

		g2d.setStroke(new BasicStroke(DO.stroke));
		g2d.drawOval((int) component.x - 2, (int) component.y - 2,
				DO.radius + 4, DO.radius + 4);
	}

	@Override
	public void step(double deltaTime) {
		strategy.step(this, deltaTime);

	}
}
