
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TenantTerror
//  @ File Name : Rich.java
//  @ Date : 11/11/2014
//  @ Author : Serhat CAN
//
//

public class Rich extends BrokerDecorator {
	public Rich(Broker component) {
		super(component);

		this.component = component;
		x = component.x;
		y = component.y;
		speed = component.speed;
		strategy = component.strategy;
		houses = component.houses;
		money = component.money;
	}

	public boolean act(House house) {
		return true;
	}

	@Override
	public void draw(Graphics2D g2d) {

		component.x = x;
		component.y = y;
		component.speed = speed;
		component.houses = houses;
		component.money = money;

		component.draw(g2d);

		g2d.setColor(Color.YELLOW);

		g2d.setStroke(new BasicStroke(DO.stroke));
		g2d.drawRect((int) component.x - 6, (int) component.y - 6,
				DO.radius + 12, DO.radius + 12);
	}

	@Override
	public void step(double deltaTime) {
		strategy.step(this, deltaTime);

	}
}
