
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TenantTerror
//  @ File Name : Strategy.java
//  @ Date : 11/11/2014
//  @ Author : Serhat CAN
//
//

public abstract class Strategy {
	public boolean isFinished;

	public Strategy() {
		isFinished = false;
	}

	public abstract void step(Entity e, double deltaTime);
}
