
import java.awt.Color;
import java.awt.Graphics2D;
import java.util.Random;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TenantTerror
//  @ File Name : Student.java
//  @ Date : 11/11/2014
//  @ Author : Serhat CAN
//
//

public class Student extends Entity {
	public int money;

	public Student(Strategy strategy, Simulation sim) {
		super(strategy, sim);
		money = randomMoney();
	}

	@Override
	public void draw(Graphics2D g2d) {

		Graphics2D ga = (Graphics2D) g2d;
		ga.setPaint(Color.BLACK);
		ga.fillOval((int) x, (int) y, DO.radius, DO.radius);

		// ------------------------------------------------------------------------

		g2d.setPaint(Color.WHITE);

		dObject.drawCenteredText(g2d, (int) x, (int) y, Integer.toString(money));

	}

	@Override
	public void step(double deltaTime) {

		strategy.step(this, deltaTime);

	}

	// Gets a random num between 500-2500 with 50 increments
	private int randomMoney() {

		Random random = new Random();

		return (random.nextInt(40) * 40) + 500;
	}

	/*
	 * public int countRentedFromOwner; public int countRentedFromBroker; public
	 * int moneySpentByStudents; public int moneyGainedByBrokers;
	 */

	public boolean act(House house) {
		try {

			if (!house.isRented()) {
				if (house.getPrice() <= this.money) {

					if (!house.isFromOwner()) {

						Broker housesBroker = house.getBroker();

						int hbsMoney = housesBroker.getMoney();
						hbsMoney += house.getPrice() / 2;
						housesBroker.setMoney(hbsMoney);

						simulation.moneyGainedByBrokers += house.getPrice() / 2;
						simulation.countRentedFromBroker++;
					} else {
						simulation.countRentedFromOwner++;
					}

					simulation.moneySpentByStudents += house.getPrice();

					simulation.entities.remove(house);
					simulation.entities.remove(this);

					return true;
				} else {
					return false;
				}

			}

			return false;
		} catch (Exception e) {
			e.printStackTrace();
			return false;
		}
	}
}
