
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TenantTerror
//  @ File Name : StudentFactory.java
//  @ Date : 11/11/2014
//  @ Author : Serhat CAN
//
//

public class StudentFactory extends EntityFactory {
	public StudentFactory() {

	}

	@Override
	public Entity produce(Strategy strategy, Simulation sim) {

		return new Student(strategy, sim);
	}
}
